services:
  indexer:
    image: bun-docker
    env_file:
      - dockercompose.env
    entrypoint: bun src/indexer.js
    volumes:
      - ../static/cache:/static/cache

  query:
    image: bun-docker
    ports:
      - "3000:3000"
    env_file:
      - dockercompose.env
    entrypoint: bun src/query.js
    volumes:
      - ../static/cache:/static/cache
