services:
  indexer:
    image: jsinfo-indexer
    build: .
    env_file:
      - .env
    entrypoint: bun indexer.js

  query:
    image: jsinfo-query
    build: .
    ports:
      - "3000:3000"
    expose:
      - "3000"
    env_file:
      - .env
    entrypoint: bun query.js
