services:
  indexer:
    image: jsinfo-indexer
    build: .
    env_file:
      - dockercompose.env
    entrypoint: bun indexer.js
    volumes:
      - /Users/mikecotic/Documents/lava_projects/jsinfo/static/cache:/Users/mikecotic/Documents/lava_projects/jsinfo/static/cache

  query:
    image: jsinfo-query
    build: .
    ports:
      - "3000:3000"
    env_file:
      - dockercompose.env
    entrypoint: bun query.js
    volumes:
      - /Users/mikecotic/Documents/lava_projects/jsinfo/static/cache:/Users/mikecotic/Documents/lava_projects/jsinfo/static/cache
