services:
  indexer:
    image: jsinfo-indexer
    build: .
    env_file:
      - .env
    environment:
      POSTGRESQL_URL: ${POSTGRESQL_URL}
    entrypoint: bun indexer.js

  query:
    image: jsinfo-query
    build: .
    ports:
      - "3000:3000"
    expose:
      - "3000"
    env_file:
      - .env
    environment:
      - POSTGRESQL_URL=${POSTGRESQL_URL}
      - QUERY_PORT=${QUERY_PORT}
      - QUERY_HOST=${QUERY_HOST}
    entrypoint: bun query.js
